version: '3.9'

services:
  # database:
  #   container_name: database
  #   image: 'mariadb:latest'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: symfony
  #     MYSQL_DATABASE: symfony
  #     MYSQL_USER: symfony
  #     MYSQL_PASSWORD: symfony
  #   ports:
  #     - '4306:3306'

  database:
    image: postgres:${POSTGRES_VERSION:-13}-alpine
    environment:
      POSTGRES_DB: symfony_docker
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: symfony
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      
  php:
    container_name: php
    build:
      context: ./
    ports:
      - '9100:9000'
    volumes:
      - ./:/var/www/symfony
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
